### ISSUE TITLE
Ignore acronym

### ISSUE THREAD

**Issue by nitnelave** [kamykn/spelunker.vim#51]
Hi, it's me again! :smile: 

Could you add an option to disable spell checking on acronyms (all-caps words)?

E.g.: 
"ABCD" -> ok
"abcd" -> error
"Abcd" -> error
"ABCDError" -> okay because Error is a word
"ABCDGabrage" -> error on "Gabrage" because it's not a word

Thanks!

**Comment by kamykn** [comment]
Hi, @nitnelave.

Thank you for suggesting. But, this is a bug that the first capitalized words following acronyms are not highlighted.
This bug was fixed at #52. Is it okay if I don't add the option?

**Comment by nitnelave** [comment]
Thanks for the quick fix!

So, the fix helps, you can see that there is a good split between all-caps and the word. However, "ABCDError" still shows an error on "ABCD". Usually, when I write all-caps, it's because it's an acronym, so I don't want it spell-checked. So even "ABCD" alone (which right now is marked as wrong) should be fine.

**Comment by kamykn** [comment]
@nitnelave 
Oh, I see.
I'm going to add new option. Thanks for the prompt reply.

**Comment by kamykn** [comment]
@nitnelave 
I'm sorry I've kept you waiting.
I've added a option to disable Acronym's spell check, so please check it.

```
" Disable acronym checking. (default: 0)
let g:spelunker_disable_acronym_checking = 1
```

**Comment by nitnelave** [comment]
Thanks, it seems to work perfectly!
